Added ACL config and change default configuration

diff --git a/plugins/rsplugin b/plugins/rsplugin
--- a/plugins/rsplugin
+++ b/plugins/rsplugin
@@ -153,7 +153,7 @@ function geo() {
             exit 1;
         fi
         if test "$licensekey" = ""; then
-            echo "Sorry, License Key cannot be blank" >&2
+            echo "Sorry, License key cannot be blank" >&2
             exit 1;
         fi
         echo "Update configuration ..."
@@ -180,6 +180,14 @@ function geoupdate_rs() {
     fi
 }
 
+#Function for view cisco ACL
+function ciscoconfig() {
+    echo "Displaying default configuration ACL Cisco ..."
+    echo ""
+    cat $RSDESTP/cisco_acl_syslog-ng.conf
+    exit
+}
+
 #Install ubiquiti parser
 function ubiquiti_parser() {
     if [ -f /usr/share/GeoIP/GeoLite2-City.mmdb ]; then
@@ -193,30 +201,26 @@ function ubiquiti_parser() {
 	    echo "Overwrite of default RSX file ..."
 	    cp $RSDESTP/99RSX-uni-ubi.conf $SYSLOGCONF/99RSX-rs.conf
             echo "Update Elastic configuration ..."
-            curl -X POST -H 'Content-Type: application/json' 'http://localhost:9200/rsx-syslog-ng/_mapping' -d \
-            '{
-               "properties" : {
-                  "geoip2" : {
-                     "properties" : {
-                        "src.geo_point" : {
-                           "type" : "geo_point"
+            curl -X PUT http://127.0.0.1:9200/_template/rsx-syslog-ng -H 'Content-Type:application/json' -d '{
+                "template":"rsx*",
+                "settings": {
+                "number_of_replicas": 1,
+                "number_of_shards": 1
+                },
+                "mappings": {
+                    "properties": {
+                        "geoip2": {
+                            "properties": {
+                                "src.geo_point": {
+                                "type": "geo_point"
+                                },
+                                "dst.geo_point": {
+                                "type": "geo_point"
+                                }
+                            }
                         }
-                     }
-                  }
-               }
-            }'
-            echo ""
-            curl -X POST -H 'Content-Type: application/json' 'http://localhost:9200/rsx-syslog-ng/_mapping' -d \
-            '{
-               "properties" : {
-                  "geoip2" : {
-                     "properties" : {
-                        "dst.geo_point" : {
-                           "type" : "geo_point"
-                        }
-                     }
-                  }
-               }
+                    }
+                }
             }'
             echo ""
             echo "Restart services ..."
@@ -239,7 +243,7 @@ clear
 banner
 #Menu
 PS3='Please enter your choice: '
-options=("Install Geo2 location data" "Update Geo2 location database" "Check Geo2 database" "Install/view ubiquiti/unifi config with Geo2" "Install PHP profile authentication - Info: Do not use ..." "Remove PHP profile auhentication - Info: Do not use ..." "Quit")
+options=("Install Geo2 location data" "Update Geo2 location database" "Check Geo2 database" "Install/view ubiquiti/unifi config with Geo2" "Install PHP profile authentication - Info: Do not use ..." "Remove PHP profile auhentication - Info: Do not use ..." "Display example configuration Cisco ACL ..." "Quit")
 select opt in "${options[@]}"
 do
     case $opt in
@@ -278,6 +282,12 @@ do
             clear
             banner
             phpauthremove
+            exit
+    ;;
+        "Display example configuration Cisco ACL ...")
+            clear
+            banner
+            ciscoconfig
             exit
     ;;
         "Quit")
